name: pull request and test
on:
  push:
    branches:
      - dev

  workflow_dispatch:
    branches:
      - dev

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Download codes
        uses: actions/checkout@v4

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Auto PR: PR Test"
          body: "this is pr test from dev to main"
          token: ${{ secrets.ACTION_TEST_TOKEN }}
          base: main
          branch: ${{ github.ref }}

  run-tests:
    name: Run Test
    needs: create-pr
    runs-on: ubuntu-latest
    steps:
      - name: Download Codes
        uses: actions/checkout@v4

      - name: Install Deps
        run: npm ci

      - name: Run Tests
        id: run-tests
        run: npm run test

      - name: Report Test Result if fail
        if: ${{ steps.run-tests.outcome }} == 'failure'
        run: echo "test failed"
