name: pull request and test
on:
  push:
    branches:
      - dev

  workflow_dispatch:
    branches:
      - dev

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Download codes
        uses: actions/checkout@v4

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Auto PR: PR Test"
          body: "this is pr test from dev to main"
          # 엑세스 토큰 필요
          token: ${{ secrets.ACTION_TEST_TOKEN }}
          base: main
          # github 컨텍스트
          branch: ${{ github.ref }}

  run-tests:
    name: Run Test
    needs: create-pr
    runs-on: ubuntu-latest
    steps:
      - name: Download Codes
        uses: actions/checkout@v4

      - name: Install Deps
        run: npm ci

      - name: Run Tests
        id: run-tests
        run: npm run test

      - name: Report Test Result if fail
        # 원래는 ${{ steps.run-tests}} 형식으로 참조하지만 if문에서는
        # ${{ ... }}를 쓰지 않는다.
        # ${{ steps }}  컨텐스트
        if: failure() && steps.run-tests.outcome  == 'failure'
        run: echo "test failed"

  fake-linting:
    name: Fake Linting For Test
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        run: echo "Linting..."

  failure-report:
    name: Failure Report
    runs-on: ubuntu-latest
    needs: [fake-linting, run-tests]
    # 이전 job에서 fail이 떳다면 true를 반환함.
    if: failure()
    steps:
      - name: Report
        run: |
          echo "Something Went Wrong"
          echo "Report..."
