name: pull request and test
on:
  push:
    branches:
      - dev

  workflow_dispatch:
env:
  NEXT_PUBLIC_DB_NAME: test-db

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v3

      - name: Download Deps
        run: npm ci

      - name: Run Tests
        run: npm run test

  build:
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v3

      - name: Download Deps
        run: npm ci

      - name: Build
        run: npm run build
