name: Deployment Project with Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v3

      # - name: Install nodejs
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "18"

      - name: Downloads Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v3

      - name: Download Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy
        run: echo "Deploy..."
